# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ieee_float_to_hex <- function(f) {
    .Call(`_ieeeConverter_ieee_float_to_hex`, f)
}

ieee_float_to_bit <- function(f) {
    .Call(`_ieeeConverter_ieee_float_to_bit`, f)
}

